package com.foliox.documentos.documento;

import java.time.Instant;
import java.util.UUID;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

@Getter
@Setter
@Table("documentos")
public class Documento {

    /** Generated by the database ({@code DEFAULT gen_random_uuid()}) — never pre-set (see design decision 9). */
    @Id
    private UUID id;

    private UUID estudioId;

    private UUID expedienteId;

    private String nombre;

    /** MinIO key {@code {estudioId}/{uuid}.pdf}. */
    private String ubicacion;

    private Instant creadoEn;
}
